FROM postgres:15
USER root
RUN apt-get update && apt-get install -y python3 python3-pip libpq-dev python3-dev python3-psycopg2
WORKDIR /docker-entrypoint-initdb.d/
COPY src/build_mock.py .
COPY src/init_postgres.py .
COPY src/ ./src/
RUN python3 build_mock.py
USER postgres
